"""phase 5 review and pull request tables

Revision ID: b7d31f0a52c4
Revises: 4ac8bdcf9b19
Create Date: 2026-09-15

Written by hand rather than autogenerated. Alembic's `revision --autogenerate` cannot run
reliably on the development machine (it loads a large import graph and dies with
E_OUTOFMEMORY on 6 GB of RAM — see BUILD_PLAN.md section 9). The tables here mirror
`app/models/review.py` exactly, and `scripts/db_inspect.py` is used to confirm the applied
result matches.

Two constraints in here carry the safety guarantee rather than merely describing data:

* ``uq_approval_per_run`` — one decision per run, at the database level. A second decision is
  a conflict, not an overwrite, even if two reviewers click at the same moment.
* ``ondelete="RESTRICT"`` on ``pull_request.approval_id`` — the approval that authorised a
  pull request cannot be deleted while that pull request exists, so the audit trail cannot be
  broken after the fact.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b7d31f0a52c4"
down_revision: str | None = "4ac8bdcf9b19"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "agent_plan",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("problem_understanding", sa.Text(), nullable=False),
        sa.Column("suspected_root_cause", sa.Text(), nullable=False),
        sa.Column("root_cause_confidence", sa.String(length=16), nullable=False),
        sa.Column("verification_strategy", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["agent_run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_plan_run", "agent_plan", ["run_id"], unique=False)

    op.create_table(
        "run_diff",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("diff_text", sa.Text(), nullable=False),
        sa.Column("diff_hash", sa.String(length=64), nullable=False),
        sa.Column("files_changed", sa.Integer(), nullable=False),
        sa.Column("lines_added", sa.Integer(), nullable=False),
        sa.Column("lines_removed", sa.Integer(), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("risk_reasons", sa.JSON(), nullable=True),
        sa.Column("risk_warnings", sa.JSON(), nullable=True),
        sa.Column("risk_blocking", sa.Boolean(), nullable=False),
        sa.Column("sensitive_paths", sa.JSON(), nullable=True),
        sa.Column("verification", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["agent_run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_diff_run", "run_diff", ["run_id"], unique=False)

    op.create_table(
        "approval",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column("diff_hash", sa.String(length=64), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["agent_run.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        # The gate, enforced by the database and not only by application code.
        sa.UniqueConstraint("run_id", name="uq_approval_per_run"),
    )
    op.create_index("ix_approval_run", "approval", ["run_id"], unique=False)

    op.create_table(
        "pull_request",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("repository_id", sa.String(length=36), nullable=False),
        sa.Column("approval_id", sa.String(length=36), nullable=False),
        sa.Column("branch", sa.String(length=255), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("html_url", sa.String(length=512), nullable=True),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["agent_run.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["repository_id"], ["repository.id"], ondelete="CASCADE"),
        # RESTRICT, not CASCADE: the approval that authorised this pull request must remain
        # for as long as the pull request does.
        sa.ForeignKeyConstraint(["approval_id"], ["approval.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pr_run", "pull_request", ["run_id"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_pr_run", table_name="pull_request")
    op.drop_table("pull_request")

    op.drop_index("ix_approval_run", table_name="approval")
    op.drop_table("approval")

    op.drop_index("ix_diff_run", table_name="run_diff")
    op.drop_table("run_diff")

    op.drop_index("ix_plan_run", table_name="agent_plan")
    op.drop_table("agent_plan")
